
import React, { useMemo, useState } from 'react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend, AreaChart, Area, LineChart, Line
} from 'recharts';
import { 
  FileText, Download, Printer, TrendingUp, Users, DollarSign, Package, Activity, Target, LayoutGrid, ArrowUpRight, Filter, Calendar, X, FileJson, FileSpreadsheet
} from 'lucide-react';
import { Influencer, Delivery, Project, Transaction } from '../types';

// Helper Components
const StatBox: React.FC<{ icon: any, label: string, value: any, color: string }> = ({ icon: Icon, label, value, color }) => (
  <div className="bg-slate-900/50 border border-slate-800 p-6 rounded-3xl">
    <div className="flex items-center justify-between mb-4">
      <Icon className={color} size={24} />
      <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">{label}</span>
    </div>
    <div className="text-3xl font-black text-slate-100">{value}</div>
  </div>
);

interface ChartCardProps {
  id: string;
  title: string;
  subtitle: string;
  icon: React.ReactNode;
  children?: React.ReactNode;
  onFilterChange?: (dates: { start: string, end: string }) => void;
}

const ChartCard: React.FC<ChartCardProps> = ({ id, title, subtitle, icon, children, onFilterChange }) => {
  const [showFilters, setShowFilters] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const handlePrint = () => {
    const printContent = document.getElementById(`section-${id}`);
    if (!printContent) return;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Report - ${title}</title>
            <script src="https://cdn.tailwindcss.com"></script>
            <style>
              @media print {
                body { background: white !important; color: black !important; padding: 20px; font-family: sans-serif; }
                .no-print { display: none !important; }
                .chart-container { width: 100% !important; height: 400px !important; }
              }
              body { background: white; color: black; padding: 40px; font-family: sans-serif; }
            </style>
          </head>
          <body>
            <div class="mb-8 border-b pb-4">
              <h1 class="text-3xl font-black uppercase tracking-tighter">${title}</h1>
              <p class="text-gray-500 font-bold">${subtitle}</p>
              ${startDate || endDate ? `<p class="text-xs mt-2 text-cyan-600">Range: ${startDate || 'Any'} to ${endDate || 'Any'}</p>` : ''}
            </div>
            <div class="chart-container">
              ${printContent.innerHTML}
            </div>
            <div class="mt-8 pt-4 border-t text-[10px] text-gray-400 font-bold uppercase">
              Generated by CreatorFlow System • ${new Date().toLocaleString()}
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 750);
    }
  };

  const applyFilters = () => {
    if (onFilterChange) {
      onFilterChange({ start: startDate, end: endDate });
    }
    setShowFilters(false);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 shadow-xl animate-in slide-in-from-bottom-2 flex flex-col relative group">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div className="flex items-start space-x-4">
          <div className="p-3 bg-slate-800 rounded-2xl group-hover:bg-slate-700 transition-colors">
            {icon}
          </div>
          <div>
            <h3 className="text-xl font-bold text-slate-50">{title}</h3>
            <p className="text-xs text-slate-500 font-medium">{subtitle}</p>
          </div>
        </div>
        
        <div className="flex items-center space-x-2">
          <button 
            onClick={() => setShowFilters(!showFilters)}
            className={`p-2 rounded-xl border transition-all ${showFilters ? 'bg-cyan-500/10 border-cyan-500/50 text-cyan-400' : 'bg-slate-800 border-slate-700 text-slate-400 hover:text-slate-200'}`}
            title="Filter Data"
          >
            <Filter size={16} />
          </button>
          
          <div className="relative">
            <button 
              onClick={() => setShowExport(!showExport)}
              className={`p-2 rounded-xl border transition-all ${showExport ? 'bg-emerald-500/10 border-emerald-500/50 text-emerald-400' : 'bg-slate-800 border-slate-700 text-slate-400 hover:text-slate-200'}`}
              title="Export Options"
            >
              <Download size={16} />
            </button>
            {showExport && (
              <>
                <div className="fixed inset-0 z-[60]" onClick={() => setShowExport(false)} />
                <div className="absolute right-0 mt-2 w-48 bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl p-2 z-[70] animate-in zoom-in-95 duration-150">
                  <button onClick={() => { handlePrint(); setShowExport(false); }} className="w-full flex items-center space-x-3 px-3 py-2.5 hover:bg-slate-800 rounded-xl text-xs font-bold text-slate-300">
                    <Printer size={14} className="text-cyan-400" />
                    <span>Print Section</span>
                  </button>
                  <button onClick={() => setShowExport(false)} className="w-full flex items-center space-x-3 px-3 py-2.5 hover:bg-slate-800 rounded-xl text-xs font-bold text-slate-300">
                    <FileText size={14} className="text-rose-400" />
                    <span>Export PDF</span>
                  </button>
                  <button onClick={() => setShowExport(false)} className="w-full flex items-center space-x-3 px-3 py-2.5 hover:bg-slate-800 rounded-xl text-xs font-bold text-slate-300">
                    <FileSpreadsheet size={14} className="text-emerald-400" />
                    <span>Export CSV</span>
                  </button>
                  <button onClick={() => setShowExport(false)} className="w-full flex items-center space-x-3 px-3 py-2.5 hover:bg-slate-800 rounded-xl text-xs font-bold text-slate-300">
                    <FileJson size={14} className="text-amber-400" />
                    <span>Export JSON</span>
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Inline Date Filter */}
      {showFilters && (
        <div className="mb-6 p-5 bg-slate-950 border border-slate-800 rounded-2xl animate-in slide-in-from-top-2 duration-200 shadow-inner">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest flex items-center">
              <Calendar size={12} className="mr-1.5" /> Date & Data Filter
            </span>
            <button onClick={() => setShowFilters(false)} className="text-slate-500 hover:text-white transition-colors">
              <X size={14} />
            </button>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="space-y-1">
              <label className="text-[8px] font-black text-slate-600 uppercase">Start Date</label>
              <input 
                type="date" 
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-300 focus:outline-none focus:border-cyan-500" 
              />
            </div>
            <div className="space-y-1">
              <label className="text-[8px] font-black text-slate-600 uppercase">End Date</label>
              <input 
                type="date" 
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-300 focus:outline-none focus:border-cyan-500" 
              />
            </div>
            <div className="flex items-end">
              <button 
                onClick={applyFilters}
                className="w-full bg-cyan-600 hover:bg-cyan-500 text-white py-2 rounded-lg text-xs font-bold transition-all shadow-lg shadow-cyan-900/20"
              >
                Apply Filters
              </button>
            </div>
          </div>
        </div>
      )}

      <div id={`section-${id}`} className="flex-1 min-h-[300px]">
        {children}
      </div>
    </div>
  );
};

interface ReportsProps {
  influencers: Influencer[];
  deliveries: Delivery[];
  projects: Project[];
  transactions: Transaction[];
}

type ReportType = 'all' | 'influencers' | 'tracking' | 'deliveries' | 'expenses';

const COLORS = ['#22d3ee', '#ec4899', '#10b981', '#f59e0b', '#3b82f6', '#6366f1'];

const Reports: React.FC<ReportsProps> = ({ influencers, deliveries, projects, transactions }) => {
  const [activeReport, setActiveReport] = useState<ReportType>('all');
  const [selectedInfluencerId, setSelectedInfluencerId] = useState<string>(influencers[0]?.id || '');
  
  // Filtering logic state
  const [dateRange, setDateRange] = useState({ start: '', end: '' });

  const selectedInfluencer = useMemo(() => 
    influencers.find(i => i.id === selectedInfluencerId) || influencers[0], 
    [influencers, selectedInfluencerId]
  );

  const trendData = useMemo(() => {
    const baseData = [
      { name: 'Jan', followers: 100, engagement: 5.2, roi: 120 },
      { name: 'Feb', followers: 150, engagement: 5.8, roi: 150 },
      { name: 'Mar', followers: 220, engagement: 6.1, roi: 190 },
      { name: 'Apr', followers: 310, engagement: 5.9, roi: 240 },
      { name: 'May', followers: 450, engagement: 6.4, roi: 310 },
      { name: 'Jun', followers: 600, engagement: 6.8, roi: 450 },
    ];

    if (!selectedInfluencer) return baseData;

    return baseData.map(d => ({
      ...d,
      followers: Math.floor(selectedInfluencer.followers * (0.8 + (Math.random() * 0.4))),
      engagement: parseFloat((selectedInfluencer.engagementRate * (0.9 + Math.random() * 0.2)).toFixed(1)),
      roi: Math.floor((selectedInfluencer.followers / 1000) * (selectedInfluencer.engagementRate / 100) * (0.5 + Math.random()))
    }));
  }, [selectedInfluencer, dateRange]);

  const productionData = useMemo(() => influencers.map(inf => ({
    name: inf.name,
    done: inf.completedVideos,
    target: inf.targetVideos,
    remaining: Math.max(0, inf.targetVideos - inf.completedVideos)
  })), [influencers, dateRange]);

  const financialData = useMemo(() => projects.map(p => {
    const actual = p.expenses.reduce((sum, item) => sum + (item.qty * item.price), 0);
    return {
      name: p.title,
      budget: p.budget,
      actual: actual,
      diff: p.budget - actual
    };
  }), [projects, dateRange]);

  const deliveryData = useMemo(() => {
    const counts: Record<string, number> = {};
    deliveries.forEach(d => { counts[d.status] = (counts[d.status] || 0) + 1; });
    return Object.keys(counts).map(key => ({ name: key, value: counts[key] }));
  }, [deliveries, dateRange]);

  const efficiencyData = useMemo(() => influencers.map(inf => ({
    name: inf.name,
    salary: inf.salary,
    engagement: inf.engagementRate,
    score: (inf.engagementRate / (inf.salary || 1)) * 100 
  })), [influencers, dateRange]);

  const tabs: { id: ReportType, label: string, icon: any }[] = [
    { id: 'all', label: 'Overview', icon: LayoutGrid },
    { id: 'influencers', label: 'Influencers', icon: Users },
    { id: 'tracking', label: 'Tracking', icon: Target },
    { id: 'deliveries', label: 'Deliveries', icon: Package },
    { id: 'expenses', label: 'Expense Flow', icon: DollarSign },
  ];

  return (
    <div className="space-y-8 pb-20">
      <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-6">
        <div>
          <h2 className="text-3xl font-black text-slate-50 tracking-tight">System Reporting Hub</h2>
          <p className="text-slate-400 text-sm">Granular analytics with per-section export and print control</p>
        </div>
        
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex p-1 bg-slate-900 border border-slate-800 rounded-xl">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveReport(tab.id)}
                className={`flex items-center space-x-2 px-4 py-2.5 rounded-lg text-xs font-bold transition-all ${
                  activeReport === tab.id ? 'bg-slate-800 text-cyan-400 shadow-sm' : 'text-slate-500 hover:text-slate-300'
                }`}
              >
                <tab.icon size={14} />
                <span>{tab.label}</span>
              </button>
            ))}
          </div>
          
          <div className="h-8 w-px bg-slate-800 mx-2 hidden sm:block" />
          
          <button 
            onClick={() => window.print()}
            className="flex items-center space-x-2 bg-gradient-to-r from-cyan-600 to-cyan-500 hover:from-cyan-500 hover:to-cyan-400 text-white px-6 py-2.5 rounded-xl font-bold transition-all shadow-xl shadow-cyan-900/20"
          >
            <Printer size={18} />
            <span>Master Export</span>
          </button>
        </div>
      </div>

      <div className="animate-in fade-in duration-500 space-y-10">
        
        {/* KPI Dashboard - Summary */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatBox icon={Users} label="Partners" value={influencers.length} color="text-cyan-400" />
          <StatBox icon={Activity} label="Videos" value={influencers.reduce((sum, i) => sum + i.completedVideos, 0)} color="text-pink-400" />
          <StatBox icon={DollarSign} label="Active Budget" value={`$${projects.reduce((sum, p) => sum + p.budget, 0).toLocaleString()}`} color="text-emerald-400" />
          <StatBox icon={Package} label="Logistics" value={deliveries.length} color="text-amber-400" />
        </div>

        {/* Influencer Specific Reporting - Example "Section Print" requirement */}
        {(activeReport === 'all' || activeReport === 'influencers') && (
          <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900/40 p-6 rounded-3xl border border-slate-800">
              <div className="flex items-center space-x-4">
                <div className="p-3 bg-pink-500/10 rounded-2xl">
                   <Users className="text-pink-500" size={24} />
                </div>
                <div>
                  <h3 className="text-xl font-black text-slate-100 uppercase tracking-tighter">Partner Specific Analysis</h3>
                  <p className="text-xs text-slate-500 font-bold uppercase">Section-level print and filter available per metric</p>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <select 
                  value={selectedInfluencerId}
                  onChange={(e) => setSelectedInfluencerId(e.target.value)}
                  className="bg-slate-950 border border-slate-800 rounded-xl px-5 py-2.5 text-sm text-slate-200 outline-none focus:border-cyan-500 transition-all font-bold"
                >
                  {influencers.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}
                </select>
                <button 
                  onClick={() => {
                    const el = document.getElementById('influencer-performance-deep-dive');
                    if (el) window.print();
                  }}
                  className="p-2.5 bg-slate-800 border border-slate-700 rounded-xl text-slate-300 hover:bg-slate-700"
                >
                  <Printer size={18} />
                </button>
              </div>
            </div>

            <div id="influencer-performance-deep-dive" className="grid grid-cols-1 xl:grid-cols-3 gap-8">
              <ChartCard 
                id="inf-growth"
                title="Follower Growth" 
                subtitle="Historical trending for selected partner"
                icon={<TrendingUp className="text-cyan-400" size={20} />}
                onFilterChange={setDateRange}
              >
                <div className="h-64 mt-4">
                  <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={trendData}>
                      <defs>
                        <linearGradient id="colGrowth" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="#22d3ee" stopOpacity={0.3}/>
                          <stop offset="95%" stopColor="#22d3ee" stopOpacity={0}/>
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                      <XAxis dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '12px' }} />
                      <Area type="monotone" dataKey="followers" stroke="#22d3ee" fillOpacity={1} fill="url(#colGrowth)" strokeWidth={3} />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              </ChartCard>

              <ChartCard 
                id="inf-eng"
                title="Engagement Curve" 
                subtitle="Daily interaction percentage fluctuation"
                icon={<Activity className="text-pink-400" size={20} />}
                onFilterChange={setDateRange}
              >
                <div className="h-64 mt-4">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={trendData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                      <XAxis dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '12px' }} />
                      <Line type="monotone" dataKey="engagement" stroke="#ec4899" strokeWidth={4} dot={{ r: 5, fill: '#ec4899', strokeWidth: 2, stroke: '#0f172a' }} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </ChartCard>

              <ChartCard 
                id="inf-roi"
                title="Revenue Yield" 
                subtitle="Calculated ROI based on spend vs engagement"
                icon={<DollarSign className="text-emerald-400" size={20} />}
                onFilterChange={setDateRange}
              >
                <div className="h-64 mt-4">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={trendData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                      <XAxis dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} />
                      <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '12px' }} cursor={{ fill: '#1e293b' }} />
                      <Bar dataKey="roi" fill="#10b981" radius={[6, 6, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </ChartCard>
            </div>
          </div>
        )}

        {/* Global Distribution Sections */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {(activeReport === 'all' || activeReport === 'expenses') && (
            <ChartCard 
              id="global-finance"
              title="Budget Utilization" 
              subtitle="Projected vs Actual spend across all active campaigns"
              icon={<FileText className="text-emerald-400" size={20} />}
              onFilterChange={setDateRange}
            >
              <div className="h-80 mt-4">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={financialData} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" horizontal={false} />
                    <XAxis type="number" stroke="#64748b" axisLine={false} tickLine={false} />
                    <YAxis type="category" dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} width={100} />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #334155' }} cursor={{ fill: '#1e293b' }} />
                    <Legend iconType="circle" />
                    <Bar dataKey="budget" name="Planned" fill="#1e293b" radius={[0, 4, 4, 0]} />
                    <Bar dataKey="actual" name="Spent" fill="#10b981" radius={[0, 4, 4, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </ChartCard>
          )}

          {(activeReport === 'all' || activeReport === 'tracking') && (
            <ChartCard 
              id="global-prod"
              title="Production Pipeline" 
              subtitle="Funnel of video completions across partners"
              icon={<Target className="text-cyan-400" size={20} />}
              onFilterChange={setDateRange}
            >
              <div className="h-80 mt-4">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={productionData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                    <XAxis dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} />
                    <YAxis stroke="#64748b" axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #334155' }} cursor={{ fill: '#1e293b' }} />
                    <Legend iconType="circle" />
                    <Bar dataKey="done" name="Completed" stackId="a" fill="#22d3ee" />
                    <Bar dataKey="remaining" name="Owed" stackId="a" fill="#1e293b" radius={[6, 6, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </ChartCard>
          )}

          {(activeReport === 'all' || activeReport === 'deliveries') && (
            <ChartCard 
              id="global-logistics"
              title="Logistics Health" 
              subtitle="Shipment status distribution for product seeding"
              icon={<Package className="text-amber-400" size={20} />}
              onFilterChange={setDateRange}
            >
              <div className="h-80 mt-4">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={deliveryData}
                      cx="50%"
                      cy="50%"
                      innerRadius={80}
                      outerRadius={100}
                      paddingAngle={8}
                      dataKey="value"
                      stroke="none"
                    >
                      {deliveryData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: 'none', borderRadius: '16px', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)' }} />
                    <Legend verticalAlign="bottom" height={36} iconType="circle" />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </ChartCard>
          )}

          {(activeReport === 'all' || activeReport === 'influencers') && (
            <ChartCard 
              id="global-efficiency"
              title="Partner Efficiency (ROI)" 
              subtitle="Impact velocity per invested dollar"
              icon={<Activity className="text-pink-400" size={20} />}
              onFilterChange={setDateRange}
            >
              <div className="h-80 mt-4">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={efficiencyData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                    <XAxis dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} />
                    <YAxis stroke="#64748b" axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #334155' }} cursor={{ fill: '#1e293b' }} />
                    <Bar dataKey="score" name="ROI Score" fill="#ec4899" radius={[6, 6, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </ChartCard>
          )}
        </div>

        {/* Global Data Table Section */}
        <div id="section-master-matrix" className="bg-slate-900 border border-slate-800 rounded-[32px] overflow-hidden shadow-2xl group/table">
          <div className="p-8 border-b border-slate-800 bg-slate-800/10 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-2xl font-black text-slate-50 tracking-tighter uppercase">Master Performance Matrix</h3>
              <p className="text-xs text-slate-500 font-bold uppercase tracking-widest">Aggregated partner performance overview</p>
            </div>
            <div className="flex items-center space-x-2">
              <button 
                onClick={() => {
                  const el = document.getElementById('section-master-matrix');
                  if (el) {
                    const printWindow = window.open('', '_blank');
                    if (printWindow) {
                      printWindow.document.write(`<html><head><title>Matrix</title><script src="https://cdn.tailwindcss.com"></script></head><body class="p-10">${el.innerHTML}</body></html>`);
                      printWindow.document.close();
                      setTimeout(() => { printWindow.print(); printWindow.close(); }, 750);
                    }
                  }
                }}
                className="p-3 bg-slate-800 border border-slate-700 text-slate-400 hover:text-cyan-400 rounded-2xl transition-all"
              >
                <Printer size={18} />
              </button>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="text-[10px] text-slate-500 uppercase tracking-widest font-black bg-slate-950/30 border-b border-slate-800">
                <tr>
                  <th className="px-8 py-6">Partner</th>
                  <th className="px-8 py-6">Retainer Fee</th>
                  <th className="px-8 py-6">Audience Size</th>
                  <th className="px-8 py-6 text-center">Engagement</th>
                  <th className="px-8 py-6 text-center">Video Progress</th>
                  <th className="px-8 py-6 text-right">Yield Score</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {influencers.map((inf) => (
                  <tr key={inf.id} className="hover:bg-slate-800/20 transition-colors">
                    <td className="px-8 py-6">
                      <div className="flex items-center space-x-3">
                        <img src={inf.avatar} className="w-10 h-10 rounded-2xl border border-slate-700 object-cover shadow-lg" alt="" />
                        <span className="font-black text-slate-100">{inf.name}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6 font-bold text-emerald-500 tracking-tight">${inf.salary.toLocaleString()}</td>
                    <td className="px-8 py-6 text-slate-400 font-black">{(inf.followers / 1000).toFixed(0)}K</td>
                    <td className="px-8 py-6 text-center font-black text-pink-400">{inf.engagementRate}%</td>
                    <td className="px-8 py-6 text-center text-slate-300 font-bold">
                      <div className="flex items-center justify-center space-x-2">
                        <div className="w-24 h-1.5 bg-slate-800 rounded-full overflow-hidden">
                          <div className="h-full bg-cyan-500" style={{ width: `${(inf.completedVideos / inf.targetVideos) * 100}%` }} />
                        </div>
                        <span className="text-[10px]">{inf.completedVideos}/{inf.targetVideos}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6 text-right font-black text-cyan-400">
                      ${(inf.salary / (inf.followers * 0.01)).toFixed(2)} / 100 Eng.
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
